/**
 * Openly licensed stock photographs used as PREVIEW imagery only (Wikimedia Commons).
 * Generated by the image pipeline; see docs/image-credits.md. These are NOT Alder & Ember products,
 * projects or customers, and must be replaced with approved photography before launch.
 * Credits are kept with the data so the licence terms (attribution, and share-alike where it applies) are met.
 */
export interface PreviewPhoto {
  /** path prefix; variants are `${file}-${w}.webp` */
  file: string;
  width: number;
  height: number;
  /** widths actually emitted */
  widths: number[];
  credit: { title: string; author: string; license: string; licenseUrl: string | null; sourceUrl: string; adapted: string };
}

export const previewPhotos: Record<string, PreviewPhoto> = {
  'hero': {
    file: '/images/preview/hero',
    width: 1920,
    height: 1307,
    widths: [640, 1280, 1920],
    credit: {"title": "Cabin next to the Frøylandsvatnet, Sandnes, Norway julesvernex2.jpg", "author": "Jules Verne Times Two", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cabin_next_to_the_Fr%C3%B8ylandsvatnet,_Sandnes,_Norway_julesvernex2.jpg", "adapted": "Resized, converted to WebP, mirrored"},
  },
  'rowan-exterior': {
    file: '/images/preview/rowan-exterior',
    width: 1280,
    height: 1707,
    widths: [640, 1280],
    credit: {"title": "Sauna cabin at Plage Hauterive.jpg", "author": "1904.CC", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sauna_cabin_at_Plage_Hauterive.jpg", "adapted": "Resized, converted to WebP"},
  },
  'alder-exterior': {
    file: '/images/preview/alder-exterior',
    width: 1280,
    height: 720,
    widths: [640, 1280],
    credit: {"title": "CottageNorway.jpg", "author": "Nuklear1234", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:CottageNorway.jpg", "adapted": "Resized, converted to WebP"},
  },
  'ember-exterior': {
    file: '/images/preview/ember-exterior',
    width: 1280,
    height: 853,
    widths: [640, 1280],
    credit: {"title": "Saunowisko w Krągu 01.jpg", "author": "www.saunowisko.pl Lucjan Morawski", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saunowisko_w_Kr%C4%85gu_01.jpg", "adapted": "Resized, converted to WebP"},
  },
  'rowan-interior': {
    file: '/images/preview/rowan-interior',
    width: 1280,
    height: 853,
    widths: [640, 1280],
    credit: {"title": "Fjällastugan sauna with heater.jpg", "author": "W.carter", "license": "CC0", "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fj%C3%A4llastugan_sauna_with_heater.jpg", "adapted": "Resized, converted to WebP"},
  },
  'alder-interior': {
    file: '/images/preview/alder-interior',
    width: 1280,
    height: 853,
    widths: [640, 1280],
    credit: {"title": "Sauna of the spa at Amantaka luxury Resort & Hotel in Luang Prabang Laos.jpg", "author": "Basile Morin", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sauna_of_the_spa_at_Amantaka_luxury_Resort_%26_Hotel_in_Luang_Prabang_Laos.jpg", "adapted": "Resized, converted to WebP"},
  },
  'ember-interior': {
    file: '/images/preview/ember-interior',
    width: 1280,
    height: 960,
    widths: [640, 1280],
    credit: {"title": "NaturTherme Templin Sauna 07.jpg", "author": "Olaf Tausch", "license": "CC BY 3.0", "licenseUrl": "https://creativecommons.org/licenses/by/3.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:NaturTherme_Templin_Sauna_07.jpg", "adapted": "Resized, converted to WebP"},
  },
  'rowan-detail': {
    file: '/images/preview/rowan-detail',
    width: 1280,
    height: 717,
    widths: [640, 1280],
    credit: {"title": "Вагонка из сибирской лиственницы.jpg", "author": "Cheburgenator", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%B0%D0%B3%D0%BE%D0%BD%D0%BA%D0%B0_%D0%B8%D0%B7_%D1%81%D0%B8%D0%B1%D0%B8%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%BB%D0%B8%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%B8%D1%86%D1%8B.jpg", "adapted": "Resized, converted to WebP"},
  },
  'alder-detail': {
    file: '/images/preview/alder-detail',
    width: 960,
    height: 1487,
    widths: [640, 960],
    credit: {"title": "Cabin overlooking the Frøylandsvatnet, Sandnes, Norway julesvernex2.jpg", "author": "Jules Verne Times Two", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cabin_overlooking_the_Fr%C3%B8ylandsvatnet,_Sandnes,_Norway_julesvernex2.jpg", "adapted": "Resized, converted to WebP"},
  },
  'ember-detail': {
    file: '/images/preview/ember-detail',
    width: 1280,
    height: 961,
    widths: [640, 1280],
    credit: {"title": "Sauna stones on heater.jpg", "author": "Santeri Viinamäki", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sauna_stones_on_heater.jpg", "adapted": "Resized, converted to WebP"},
  },
  'detail-timber': {
    file: '/images/preview/detail-timber',
    width: 1280,
    height: 853,
    widths: [640, 1280],
    credit: {"title": "2012-366-20 Because Sunset Light Makes Everything Look Better (6734734519).jpg", "author": "cogdogblog", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:2012-366-20_Because_Sunset_Light_Makes_Everything_Look_Better_(6734734519).jpg", "adapted": "Resized, converted to WebP, colour saturation reduced 45% and slightly darkened"},
  },
  'detail-interior-finish': {
    file: '/images/preview/detail-interior-finish',
    width: 1280,
    height: 960,
    widths: [640, 1280],
    credit: {"title": "Sauna in pancevo.jpg", "author": "Unknown (public domain)", "license": "Public domain", "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sauna_in_pancevo.jpg", "adapted": "Resized, converted to WebP"},
  },
  'detail-construction': {
    file: '/images/preview/detail-construction',
    width: 1280,
    height: 946,
    widths: [640, 1280],
    credit: {"title": "Corner of observation deck at Nørre Vorupør.jpg", "author": "W.carter", "license": "CC0", "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Corner_of_observation_deck_at_N%C3%B8rre_Vorup%C3%B8r.jpg", "adapted": "Resized, converted to WebP"},
  },
  'detail-glazing-heater': {
    file: '/images/preview/detail-glazing-heater',
    width: 1280,
    height: 853,
    widths: [640, 1280],
    credit: {"title": "Barrel sauna in Lahälla 5.jpg", "author": "W.carter", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barrel_sauna_in_Lah%C3%A4lla_5.jpg", "adapted": "Resized, converted to WebP"},
  },
  'site-access': {
    file: '/images/preview/site-access',
    width: 960,
    height: 1440,
    widths: [640, 960],
    credit: {"title": "Brick garden steps Walled Garden at Parham House, West Sussex, England.jpg", "author": "Acabashi", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brick_garden_steps_Walled_Garden_at_Parham_House,_West_Sussex,_England.jpg", "adapted": "Resized, converted to WebP"},
  },
  'installation-process': {
    file: '/images/preview/installation-process',
    width: 1280,
    height: 1280,
    widths: [640, 1280],
    credit: {"title": "Tuttisauna.jpg", "author": "Ville-Matias Parkkonen", "license": "CC0", "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/", "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tuttisauna.jpg", "adapted": "Resized, converted to WebP"},
  },
};
